### ISSUE TITLE
Java 14 Support?

### ISSUE THREAD

**Issue by gary-archer** [electronicarts/ea-async#52]
Nice library guys - have been using it for a while - makes non blocking Rest API code much easier to write reliably.

Just wondered if it could be updated to support the latest Java, which I was trying to use?
I believe the below issue is related to the version of ASM dependencies.

Not massively urgent, but nice to keep your library working with latest versions.

_Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 58
	at com.ea.async.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
	at com.ea.async.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at com.ea.async.shaded.org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
	at com.ea.async.instrumentation.Transformer.transform(Transformer.java:150)_

**Comment by Mart-Bogdan** [comment]
Looks like it could be tended with this PR https://github.com/electronicarts/ea-async/pull/51
